branch-defaults:
  default:
    environment:
deploy:
<<<<<<< HEAD
  artifact: www/Archive.zip1
||||||| 4daca83
  artifact: www/Archive.zip1
=======
  artifact: www/Archive.zip1
>>>>>>> d66e05c0ec82598b3190dc522095b97b83bf2b2e
environment-defaults:
  udagram-api:
    branch: null
    repository: null
global:
  application_name: udagram
  default_ec2_keyname: null
  default_platform: Node.js 16 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: default
  sc: null
  workspace_type: Application
